stages:
  - build

build-images:
  stage: build
  image: docker:latest
  script:
    - apk --no-cache add make bash
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -f Dockerfile -t "${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}:${CI_COMMIT_SHA:0:8}" --build-arg GITLAB_USER=${GITLAB_USER} --build-arg GITLAB_TOKEN=${GITLAB_TOKEN} . 
    - docker tag "${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}:${CI_COMMIT_SHA:0:8}" "${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}:latest"
    - docker push "${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}:${CI_COMMIT_SHA:0:8}" 
    - docker push "${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}:latest"
  only:
    - master 
  services:
    - docker:dind
